# 5.1 Print

In [2]:
print('hello there!!!')

hello there!!!


In [1]:
print("viona is here :D")

viona is here :D


In [3]:
print("Soooo......")

Soooo......


In [4]:
print("you can keep me...")

you can keep me...


In [5]:
print('EHEHEHEEHHEHEHEHEHE :*')

EHEHEHEEHHEHEHEHEHE :*


In [2]:
print("LIFE IS NEVER FLAT")

LIFE IS NEVER FLAT


In [3]:
print('Algorithm is really "funny"')

Algorithm is really "funny"


In [4]:
jumlah_mahasiswa = 84
uang_di_dompet = 100000
print(jumlah_mahasiswa)
print(uang_di_dompet)
total_uang = (jumlah_mahasiswa*uang_di_dompet)
print(total_uang)

84
100000
8400000


In [5]:
nama_depan = 'Ni Komang '
nama_tengah = 'Viona Amelia '
nama_belakang = 'Putri'
print(nama_depan + nama_tengah + nama_belakang)

Ni Komang Viona Amelia Putri


# 5.2 Input

In [6]:
nama = input("who's your name? ")
kegiatan = input('what are you doing now, '+ nama + "? ")
print("keep fight " + nama + "! " )

who's your name? Viona
what are you doing now, Viona? Studying
keep fight Viona! 


# 5.3 Tipe Data pada Python

(str) (int)

In [7]:
uang_di_dompet = input("Berapa jumlah uang di dompet lo? ")
uang_di_bank = input("Eh saldo lo di Bank berapa? ")
print("Total uang yang dimiliki adalah "+ uang_di_dompet + uang_di_bank)

Berapa jumlah uang di dompet lo? 50000
Eh saldo lo di Bank berapa? 1000000
Total uang yang dimiliki adalah 500001000000


In [15]:
uang_di_dompet = 500000
uang_di_bank = 2000000
total_uang = int(uang_di_dompet) + (uang_di_bank)
print("Total uang yang dimiliki adalah Rp " + str(total_uang))

Total uang yang dimiliki adalah Rp 2500000


In [14]:
uang_di_dompet = input("Berapa jumlah uang di dompet lo? ")
uang_di_bank = input("Eh saldo lo di Bank berapa? ")
total_uang = int(uang_di_dompet) + int(uang_di_bank)
print("Total uang yang dimiliki adalah Rp " + str(total_uang))

Berapa jumlah uang di dompet lo? 500000
Eh saldo lo di Bank berapa? 2000000
Total uang yang dimiliki adalah Rp 2500000


# Cara Melihat Tipe Data Tiap Variabel

In [11]:
type(uang_di_dompet)

str

In [12]:
type(uang_di_bank)

str

In [13]:
type(total_uang)

int

# Contoh Program penjumlahan dua bilangan dengan menggunakan perintah input dan print

(float)

In [20]:
bilangan_genap = input("Masukkan bilangan genap <= 10 : ")
bilangan_ganjil = input("Masukkan bilangan ganjil <= 10 : ")
jumlah = float(bilangan_genap) + float(bilangan_ganjil)
print("Hasil penjumlahannya adalah " + str(jumlah)) 

Masukkan bilangan genap <= 10 : 8
Masukkan bilangan ganjil <= 10 : 5
Hasil penjumlahannya adalah 13.0


# 5.4 Formatted String

In [29]:
nama = "Viona"
umur = "18 tahun"
pekerjaan = "mahasiswi"
institusi = "Universitas Udayana"
print("Seorang gadis bernama " + nama + " berumur " + umur + " adalah seorang " + pekerjaan + " di " + institusi + "." )

Seorang gadis bernama Viona berumur 18 tahun adalah seorang mahasiswi di Universitas Udayana.


In [32]:
print(f"Seorang gadis bernama {nama} berumur {umur} adalah seorang {pekerjaan} di {institusi}.")

Seorang gadis bernama Viona berumur 18 tahun adalah seorang mahasiswi di Universitas Udayana.


In [33]:
print(f'Seorang gadis bernama {nama} berumur {umur} adalah seorang {pekerjaan} di {institusi}.')

Seorang gadis bernama Viona berumur 18 tahun adalah seorang mahasiswi di Universitas Udayana.


# 5.5 String Index

In [36]:
kelas = "kelas algoritma matematika"

In [37]:
print(kelas[0:5])

kelas


In [38]:
print(kelas[2:-4])

las algoritma matema


In [44]:
print(kelas[1:-2:2])

ea loim aeai


In [45]:
print(kelas[:-5])

kelas algoritma matem


In [46]:
print(kelas[:3])

kel


In [47]:
print(kelas[:])

kelas algoritma matematika


# 5.6 Strings Methods

In [11]:
guess_who = "the cutest girl in the world"

In [12]:
print(len(guess_who))

28


In [13]:
guess_who.upper()

'THE CUTEST GIRL IN THE WORLD'

In [14]:
guess_who.lower()

'the cutest girl in the world'

In [15]:
guess_who.find("Vayona")

-1

In [20]:
guess_who.find("cutest")

4

In [21]:
guess_who.find("girl")

11

In [22]:
guess_who.find("in the world")

16

In [23]:
guess_who.find("Cutest")

-1

In [24]:
guess_who.replace("cutest" , "prettiest")

'the prettiest girl in the world'

In [25]:
guess_who.replace("Cutest" , "prettiest")

'the cutest girl in the world'

In [26]:
print("cutest" in guess_who)

True


In [28]:
print("Girl" in guess_who)

False


# 5.7 Operasi Matematika di Python

     Penjumlahan (+), contoh: 2+5 = 7
 
     Pengurangan (-), contoh: 2-5 = -3
 
     Perkalian (*), contoh: 2*5 = 10
 
     Pembagian (/), contoh: 8/3 = 2.6666
 
     Pembulatan pembagian (//), contoh: 8//3 = 2
 
     Modulo (%), contoh: 8%3 = 2
 
     Pemangkatan (**), contoh: 2**3 = 8
 
     Augmented operator: contoh: x = 3, x+ = 1 artinya x = x + 1. Berlaku juga pada pengurangan dan perkalian.

In [63]:
print(2+5)

7


In [64]:
print(2-5)

-3


In [65]:
print(2*5)

10


In [66]:
print(8/3)

2.6666666666666665


In [67]:
print(8//3)

2


In [68]:
print(8%3)

2


In [69]:
print(2**3)

8


In [72]:
x=3
x+=4
print(x)

7


In [73]:
x=8
x-=3
print(x)

5


In [74]:
x=2
x*=4
print(x)

8


# 5.8 Operator Perbandingan di Python

Lebih besar (>), contoh: x = 8 > 5

Lebih kecil (<), contoh: x = 5 < 8

Lebih besar sama dengan (>=), contoh: x = 8 >= 5

Lebih kecil sama dengan (<=), contoh: x = 5 <= 8

Sama dengan (==), contoh: x = 5 == 5

Tidak sama dengan (!=), contoh: x = 5 != 7

In [75]:
x=8>5
print(x)

True


In [82]:
x=5>8
print(x)

False


In [76]:
x=5<8
print(x)

True


In [83]:
x=8<5
print(x)

False


In [77]:
x=8>=5
print(x)

True


In [84]:
x=5>=8
print(x)

False


In [79]:
x=5<=8
print(x)

True


In [85]:
x=8<=5
print(x)

False


In [80]:
x=5==5
print(x)

True


In [86]:
x=5==6
print(x)

False


In [81]:
x=5!=7
print(x)

True


In [87]:
x=5!=5
print(x)

False


# 5.9 Operator Logika di Python

and, or, not

In [88]:
buah_naga = 20
buah_alpukat = 10
print(buah_naga > 15 and buah_alpukat < 20 )

True


In [89]:
print(buah_naga > 22 or buah_alpukat < 17)

True


In [90]:
print(buah_naga > 25 or buah_alpukat > 15)

False


In [92]:
print(not(buah_naga < 15 or buah_alpukat > 15))

True


# 5.10 Operator if dalam Python

In [34]:
ipk = float(input("IPK anda adalah "))
if ipk >= 4.0:
    print("Anda mendapat nilai A")
    print("Anda sangatlah Luar Biasa!")
if ipk < 4.0 and ipk >= 3.5:
    print("Anda mendapat nilai B+")
    print("Prestasimu sudah sangat bagus!")
if ipk >= 3.0 and ipk < 3.5:
    print("Anda mendapat nilai B")
    print("Sudah bagus! Ayo Tingkatkan lagi!")
if ipk >= 2.5 and ipk < 3.0:
    print("Anda mendapat nilai C+")
    print("Lain kali musti lebih baik lagi yaaa!")
if ipk <= 2.5 and ipk < 2.0:
    print("Anda mendapat nilai C")
    print("Coba lagi ok")

IPK anda adalah 4.0
Anda mendapat nilai A
Anda sangatlah Luar Biasa!


In [36]:
ipk = float(input("IPK anda adalah "))
if ipk >= 4.0:
    print("Anda mendapat nilai A")
    print("Anda sangatlah Luar Biasa!")
elif ipk >= 3.5:
    print("Anda mendapat nilai B+")
    print("Prestasimu sudah sangat bagus!")
elif ipk >= 3.0:
    print("Anda mendapat nilai B")
    print("Sudah bagus! Ayo Tingkatkan lagi!")
elif ipk >= 2.5:
    print("Anda mendapat nilai C+")
    print("Lain kali musti lebih baik lagi yaaa!")
else:
    print("Anda mendapat nilai C")
    print("Coba lagi ok")

IPK anda adalah 2.4
Anda mendapat nilai C
Coba lagi ok


# Latihan: Buatlah program yang merubah tinggi badan seseorang dari cm ke inci atau sebaliknya dari inci ke cm

In [46]:
tinggi = float(input("Tinggimu berapa, Viona? "))
cm_atau_inci = input("Tingginya dalam cm atau inci? ")
if cm_atau_inci.upper() == 'CM':
    tinggi = tinggi*0.394
    print("Tinggi anda adalah " + str(tinggi) + " inci")
elif cm_atau_inci.upper() == "INCI" :
    tinggi = tinggi/0.394
    print(f"Tinggi anda adalah {tinggi} cm")

Tinggimu berapa, Viona? 160
Tingginya dalam cm atau inci? cm
Tinggi anda adalah 63.040000000000006 inci


# 5.11 While loop

In [44]:
a = 0
while a < 5 :
    print("Bilangan " + str(a) + " masih dibawah 5")
    a += 1

Bilangan 0 masih dibawah 5
Bilangan 1 masih dibawah 5
Bilangan 2 masih dibawah 5
Bilangan 3 masih dibawah 5
Bilangan 4 masih dibawah 5


In [47]:
a = 0
while a < 6 :
    print(a * '*')
    a += 1


*
**
***
****
*****


# 5.12 List di Python

In [48]:
warna = ['merah', 'kuning', 'hijau', 'biru']
print(warna)

['merah', 'kuning', 'hijau', 'biru']


In [49]:
bts = ['Kim Namjoon', 'Kim Seokjin', 'Min Yoongi', 'Jung Hoseok', 'Park Jimin', 'Kim Taehyung', 'Jeon Jungkook']
print(bts)

['Kim Namjoon', 'Kim Seokjin', 'Min Yoongi', 'Jung Hoseok', 'Park Jimin', 'Kim Taehyung', 'Jeon Jungkook']


In [50]:
print(bts[0])

Kim Namjoon


In [51]:
print(bts[-1])

Jeon Jungkook


In [52]:
print(bts[-3])

Park Jimin


In [53]:
print(bts[5])

Kim Taehyung


In [54]:
bts[5] = 'V'
print(bts)

['Kim Namjoon', 'Kim Seokjin', 'Min Yoongi', 'Jung Hoseok', 'Park Jimin', 'V', 'Jeon Jungkook']


In [55]:
print(bts[0:4])

['Kim Namjoon', 'Kim Seokjin', 'Min Yoongi', 'Jung Hoseok']


In [56]:
# tidak merubah list
print(bts)

['Kim Namjoon', 'Kim Seokjin', 'Min Yoongi', 'Jung Hoseok', 'Park Jimin', 'V', 'Jeon Jungkook']


# 5.13 Metoda List

In [58]:
prettiest_ofc= ['Liana', 'Dhea', 'Ce Meli']
prettiest_ofc.append('Viona')
print(prettiest_ofc)

['Liana', 'Dhea', 'Ce Meli', 'Viona']


In [60]:
prettiest_ofc.insert(0,'Angel')
print(prettiest_ofc)

['Angel', 'Liana', 'Dhea', 'Ce Meli', 'Viona']


In [61]:
prettiest_ofc.remove('Angel')
print(prettiest_ofc)

['Liana', 'Dhea', 'Ce Meli', 'Viona']


In [62]:
print('Angel' in prettiest_ofc)

False


In [63]:
print('Viona' in prettiest_ofc)

True


In [64]:
print(len(prettiest_ofc))

4


# 5.14 For loop

In [66]:
kertas = ['Buffalo', 'Manila', 'Jagung', 'Flanel', 'HVS']
for jenis in kertas :
    print(jenis)

Buffalo
Manila
Jagung
Flanel
HVS


In [67]:
i = 0
while i < len(kertas):
    print(kertas[i])
    i += 1

Buffalo
Manila
Jagung
Flanel
HVS


# 5.15 Fungsi Range

In [68]:
angka = range(5)
print(angka)

range(0, 5)


In [69]:
for isi in angka :
    print(isi)

0
1
2
3
4


In [70]:
for isi in range(5,15) :
    print(isi)

5
6
7
8
9
10
11
12
13
14


In [71]:
for isi in range(0,15,3) :
    print(isi)

0
3
6
9
12


# LATIHAN

1. Buatlah program untuk mencari nilai terbesar di dalam suatu list.
   
   jawaban :

In [73]:
data = [1,3,5,6,3,4,2,8,5,6,10,2,3,1]
terbesar = data[0]
for i in range(len(data)) :
    if data[i] > terbesar :
        terbesar = data[i]
print(terbesar)

10


In [74]:
data = [1,3,5,6,3,4,2,8,5,6,10,2,3,1]
terbesar = data[0]
for angka in data :
    if angka > terbesar :
        terbesar = angka
print(terbesar)

10


2. Buatlah program untuk membuat anggota list menjadi unik dengan kata lain tidak ada anggota list yang kembar.
   
   Jawaban :

In [76]:
angka = [1,2,3,4,4,5,6,5,6,7,8,9,7,8,7,10]
angka_unik = []
for anggota in angka :
    if anggota not in angka_unik :
        angka_unik.append(anggota)
print(angka_unik)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# 5.16 List 2 Dimensi

In [78]:
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matrik)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [79]:
matrik[1]

[5, 6, 7, 8]

In [80]:
matrik[0]

[1, 2, 3, 4]

In [82]:
matrik[3]

[13, 14, 15, 16]

In [83]:
matrik[-1]

[13, 14, 15, 16]

In [84]:
matrik[0][1]

2

In [85]:
matrik[0][3]

4

In [86]:
matrik[3][3]

16

In [88]:
matrik[3][3]=500
print(matrik[3][3])

500


In [89]:
matrik

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 500]]

In [90]:
for baris in matrik :
    print(baris)
    for kolom in baris :
        print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 500]
13
14
15
500


# 5.17 Tuples

In [91]:
angka = 0,1,1,2,3,3,4,5

In [92]:
print(angka[0])

0


In [93]:
print(angka[0:4])

(0, 1, 1, 2)


In [94]:
for isi in angka[0:4]:
    print(isi)

0
1
1
2


In [95]:
angka[0]=10

TypeError: 'tuple' object does not support item assignment

In [96]:
angka.append(10)

AttributeError: 'tuple' object has no attribute 'append'

In [102]:
angka.remove[5]

AttributeError: 'tuple' object has no attribute 'remove'

In [104]:
angka[0]=10
print(angka[0])

TypeError: 'tuple' object does not support item assignment

In [107]:
angka.count(3)

2

In [108]:
angka.index(3)

4

In [109]:
angka.index(5)

7

# 5.18 Dictionaries

In [110]:
data_orang = {
    "nama" : "Viona Amelia",
    "umur" : 18,
    "apakah_singel" : False
}

In [111]:
print(data_orang['nama'])

Viona Amelia


In [112]:
print(data_orang['Nama'])

KeyError: 'Nama'

In [113]:
print(data_orang.get('nama'))

Viona Amelia


In [114]:
print(data_orang.get('Nama'))

None


In [115]:
print(data_orang.get('tangga_lahir'))

None


In [116]:
print(data_orang.get('tanggal_lahir', '2-2-2022'))

2-2-2022


In [117]:
print(data_orang)

{'nama': 'Viona Amelia', 'umur': 18, 'apakah_singel': False}


In [118]:
print(data_orang["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [119]:
print(data_orang['tanggal_lahir'])

KeyError: 'tanggal_lahir'

In [120]:
data_orang['HP'] = '089876543210'

In [121]:
print(data_orang["HP"])

089876543210


In [122]:
print(data_orang)

{'nama': 'Viona Amelia', 'umur': 18, 'apakah_singel': False, 'HP': '089876543210'}


# LATIHAN

Buatlah program untuk merubah nomor HP yang tadinya berupa angka menjadi sebutan bilangan tersebut. Misalnya angka 0812 akan menjadi nol delapan satu dua.

In [124]:
angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan"
}

In [125]:
nomor_HP = input("Masukkan nomor HP anda ")
nomor_angka = ""
for isi in nomor_HP:
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

Masukkan nomor HP anda 08987654320
nol delapan sembilan delapan tujuh enam lima empat tiga dua nol 


In [136]:
def full_name(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [137]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_name(first_name,last_name)

Nama depan anda adalah Viona
Nama belakang anda adalah Amelia
Nama lengkapnya adalah Viona Amelia


# 5.19.1 Tugas dan Fungsi pada Python

In [138]:
def waktu_sampai(jarak,kecepatan) :
    waktu = jarak/kecepatan
    print(waktu)

In [139]:
def waktu_tempuh(jarak,kecepatan) :
    waktu = jarak/kecepatan
    return waktu

In [140]:
waktu_sampai(100,80)

1.25


In [141]:
waktu_tempuh(100,80)

1.25

In [142]:
a = waktu_sampai(100,80)
print(a)

1.25
None


In [143]:
b = waktu_tempuh(100,80)
print(b)

1.25


# LATIHAN

Buatlah program yang menggunakan fungsi Python untuk menghitung luas segitiga, lingkaran, persegi dan persegi panjang. Selain itu berikan peringatan bagi bidang lain yang tidak termasuk perhitungan.

In [144]:
import numpy as np

In [145]:
def luas_segitiga(alas,tinggi) :
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari) :
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi) : 
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar) :
    luas = panjang*lebar
    return luas

In [1]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI' or (jenis_bidang.upper() == 'BUJUR SANGKAR'): 
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah 1ebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Oops! Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan yang tertera hanya ada SEGITIGA, LINGKARAN, PERSEGI dan PERSEGI PANJANG.")
    print('Terimakasih')

Tulis jenis bidangnya Jajar Genjang
Oops! Maaf bidang Jajar Genjang yang anda masukkan tidak ada.
Pilihan yang tertera hanya ada SEGITIGA, LINGKARAN, PERSEGI dan PERSEGI PANJANG.
Terimakasih


# 5.20 Numpy

# 5.20.1 Perintah Dasar pada Numpy

In [3]:
import numpy as np

In [4]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [5]:
b = np.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [6]:
c = np.array([[[0,1,2,3],[4,5,6,7],[8,9,8,7],[6,5,4,3],[1,2,3,4],[5,6,7,8]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]
  [8 9 8 7]
  [6 5 4 3]
  [1 2 3 4]
  [5 6 7 8]]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

3

In [10]:
a.shape

(5,)

In [11]:
b.shape

(2, 4)

In [13]:
c.shape

(1, 6, 4)

# 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [14]:
import numpy as np

In [15]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
d[0,3]

4

In [17]:
d[1,2]

7

In [18]:
d[1,:]

array([5, 6, 7, 8])

In [19]:
d[0,:]

array([1, 2, 3, 4])

In [20]:
d[:,3]

array([ 4,  8, 12])

In [21]:
d[:,1]

array([ 2,  6, 10])

In [22]:
d[0,1:3]

array([2, 3])

In [23]:
d[1,1:2]

array([6])

In [24]:
d[1,1:3]

array([6, 7])

In [25]:
d[0,1:3:2]

array([2])

In [26]:
d[0,0] = 100
print(d)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [27]:
d[0,3] = 100
print(d)

[[100   2   3 100]
 [  5   6   7   8]
 [  9  10  11  12]]


# 5.20.3 Matrix pada Numpy

In [28]:
import numpy as np

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [40]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [41]:
np.random.rand(4,3)

array([[0.77376686, 0.53341141, 0.07799346],
       [0.82333897, 0.12879148, 0.15851616],
       [0.57058893, 0.69164486, 0.41427446],
       [0.55477074, 0.81825326, 0.80896646]])

In [42]:
np.random.randint(1,10,size=(3,4))

array([[7, 8, 4, 3],
       [9, 7, 2, 9],
       [4, 8, 6, 8]])

In [43]:
np.random.randint(5,15,size=(3,4))

array([[ 5,  5,  6,  5],
       [ 5, 14,  5,  8],
       [10,  5, 11,  7]])

# Latihan: Buatlah matrik ukuran 10 x10 berikut dengan menggunakan Numpy

In [44]:
import numpy as np

In [46]:
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [47]:
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [48]:
c = 9*b
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [49]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [51]:
c[1:-1,1:-1] = f
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [56]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [60]:
h = np.ones((4,4))*2
i = np.identity(4) * 7
j = h + i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [61]:
c[3:-3,3:-3] = j
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [62]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


# 5.20.4 Copy pada Numpy

In [63]:
import numpy as np

In [64]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [65]:
b = a
print(b)

[1 2 3 4 5]


In [66]:
b[0] = 10
print(b)

[10  2  3  4  5]


In [67]:
print(a)

[10  2  3  4  5]


In [68]:
c = np.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [69]:
d = c.copy()
print(d)

[1 2 3 4 5]


In [70]:
d[0] = 10
print(d)

[10  2  3  4  5]


In [71]:
d[1] = 100
print(d)

[ 10 100   3   4   5]


In [72]:
print(c)

[1 2 3 4 5]


# 5.20.5 Operasi Matematika pada Numpy

In [73]:
a+2

array([12,  4,  5,  6,  7])

In [74]:
a-2

array([8, 0, 1, 2, 3])

In [75]:
a*2

array([20,  4,  6,  8, 10])

In [76]:
a/2

array([5. , 1. , 1.5, 2. , 2.5])

In [77]:
a**2

array([100,   4,   9,  16,  25], dtype=int32)

In [78]:
b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [79]:
a+b

array([16,  9, 11, 13, 15])

In [80]:
a-b

array([ 4, -5, -5, -5, -5])

In [81]:
a*b

array([60, 14, 24, 36, 50])

In [82]:
a/b

array([1.66666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [83]:
b**a

array([60466176,       49,      512,     6561,   100000], dtype=int32)

In [84]:
np.cos(a)

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [85]:
np.cos(b)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [86]:
np.tan(a)

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [88]:
np.sinh(a)

array([1.10132329e+04, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
       7.42032106e+01])

In [89]:
np.cosh(a)

array([1.10132329e+04, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01])

In [90]:
np.tanh(a)

array([1.        , 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [91]:
np.sqrt(a)

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

# 5.20.6 Perkalian Matrik pada Numpy

In [93]:
import numpy as np

In [96]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [97]:
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [99]:
c = a*b
print(c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [100]:
d = np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [101]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [103]:
f = np.matmul(a,e)
print(f)

[[130 140]
 [322 348]]


In [104]:
g = a*e

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

# 5.20.7 min, max, dan sum pada Numpy

In [105]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [106]:
b = np.min(a)
print(b)

1


In [107]:
c = np.min(a,axis=0)
print(c)

[1 2 3 4]


In [108]:
d = np.min(a,axis=1)
print(d)

[1 5 9]


In [110]:
e = np.max(a)
print(e)

12


In [111]:
f = np.max(a,axis=0)
print(f)

[ 9 10 11 12]


In [112]:
g = np.max(a,axis=1)
print(g)

[ 4  8 12]


In [113]:
h = np.sum(a)
print(h)

78


In [115]:
h = np.sum(a,axis=0)
print(h)

[15 18 21 24]


In [117]:
i = np.sum(a,axis=1)
print(i)

[10 26 42]
